package net.matos.elementalrealms.effect;

import net.matos.elementalrealms.util.ModTags;

import net.minecraft.core.Holder;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffectCategory;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.UUID;

public class GoldenBloomEffect extends MobEffect {

    private static final Logger LOGGER = LoggerFactory.getLogger("ElementalRealms");

    // UUID generated by UUIDGen (make sure this is the same as the one you generated earlier)
    public static final UUID GOLDEN_BLOOM_SPEED_BOOST_UUID = UUID.fromString("1359cf6e-de59-4710-835a-68caf0b7d864");

    public static final AttributeModifier GOLDEN_BLOOM_SPEED_BOOST =
            new AttributeModifier(GOLDEN_BLOOM_SPEED_BOOST_UUID, 0.1D, AttributeModifier.Operation.ADD_MULTIPLIED_TOTAL);

    public GoldenBloomEffect(MobEffectCategory category, int color) {
        super(category, color);
    }

    @Override
    public boolean applyEffectTick(LivingEntity entity, int amplifier) {
        // Regeneration effect
        if (entity.getHealth() < entity.getMaxHealth()) {
            float regenAmount = 0.5F + amplifier * 0.2F;
            entity.heal(regenAmount);
        }

        // Saturation every 5 seconds
        if (entity.tickCount % 100 == 0 && entity instanceof Player player) {
            if (player.getFoodData().needsFood()) {
                player.getFoodData().eat(1, 0.3F);
            }
        }

        // Apply the speed boost when standing on FUNGUS_BLOCKS
        applyFungusBoost(entity);

        return true;
    }

    private void applyFungusBoost(LivingEntity entity) {
        if (entity.level().isClientSide) return;

        Level level = entity.level();
        BlockPos blockPos = entity.blockPosition().below();
        BlockState blockState = level.getBlockState(blockPos);

        var attributes = entity.getAttribute(Attributes.MOVEMENT_SPEED);

        // Apply speed boost when standing on FUNGUS_BLOCKS
        if (blockState.is(ModTags.Blocks.FUNGUS_BLOCKS)) {
            if (attributes != null && !attributes.hasModifier(GOLDEN_BLOOM_SPEED_BOOST)) {
                attributes.addTransientModifier(GOLDEN_BLOOM_SPEED_BOOST);
                LOGGER.info("Golden Bloom effect: speed boosted on {}", blockState.getBlock().getName().getString());
            }
        } else {
            // Remove speed boost when not standing on FUNGUS_BLOCKS
            if (attributes != null && attributes.hasModifier(GOLDEN_BLOOM_SPEED_BOOST)) {
                attributes.removeModifier(GOLDEN_BLOOM_SPEED_BOOST);
                LOGGER.info("Golden Bloom effect: speed boost removed");
            }
        }
    }

    @Override
    public boolean shouldApplyEffectTickThisTick(int duration, int amplifier) {
        return true;
    }

    @Override
    public boolean isInstantenous() {
        return false;
    }

    @Override
    public MobEffect addAttributeModifier(Holder<Attribute> pAttribute, ResourceLocation pId, double pAmount, AttributeModifier.Operation pOperation) {
        return super.addAttributeModifier(pAttribute, pId, pAmount, pOperation);
    }
}
